### ISSUE TITLE
Semanticate specific latinism

### ISSUE THREAD

**Issue by Gragt** [iesegnu/dorothy-m-richardson_pointed-roofs#11]
Chapter 1, line 96: *ad hominem* is [part of a list of latinisms that are always italicised to avoid confusion](https://standardebooks.org/manual/1.6.4/8-typography#8.9.1.1). The leading *argumentum* should probably be included in this because it is part of the same expression.

The corresponding entry in `se-lint-ignore.xhtml` can be removed since it won’t be triggered with this change.

**Comment by iesegnu** [comment]
Alright, I did this.
