### ISSUE TITLE
Remove trailing commas from <span> elements for language

### ISSUE THREAD

**Issue by Gragt** [iesegnu/dorothy-m-richardson_pointed-roofs#3]
`<span>` elements with language semantics sometimes contain trailing commas. [Treat them as italics](https://standardebooks.org/manual/1.6.4/single-page#8.2.5) and keep them out of these elements—it will also make it easier to substitute those `span` elements for `i` if it is decided. They can be found throughout the project with `,</span>`.

**Comment by iesegnu** [comment]
Thanks, done!
