### ISSUE TITLE
Remove quotation marks from title semantics

### ISSUE THREAD

**Issue by Gragt** [iesegnu/dorothy-m-richardson_pointed-roofs#5]
Chapter 1, lines 19, 23, and 24: quotation marks should be outside of the `<span>` elements for song titles unless they are specifically part of the titles.

**Comment by iesegnu** [comment]
Thanks, done!

**Comment by Gragt** [comment]
Line 19, we have `<span epub:type="se:name.music.song">“The Wearin’ o’ the Green.</span>`. You removed the closing quote but the opening one is still enclosed inside the `span`. There is also the trailing full stop that should be moved outside. The idea here is to strictly target only the actual song title.
Line 24: similarly, there are two instances of *Abide with Me*, both with single quotes and one with a comma that should be moved outside of the `<span>` elements.

**Comment by iesegnu** [comment]
Sorry, I missed those. Fixed them now.

**Comment by Gragt** [comment]
Great! We’re getting there.
