### ISSUE TITLE
Semanticate works

### ISSUE THREAD

**Issue by Gragt** [iesegnu/dorothy-m-richardson_pointed-roofs#6]
* Chapter 1, line 23: *Contemporary Review* (pluralised in the text because several editions are handled at once) is a magazine.
* Chapter 1, line 122: two book names should be semanticated—one is a complete title even stretched. You specifically want to target *The Voyage of the Beeeeeeagle* and *Poetical Works*.
* Chapter 2, line 49: *La Maison déserte* is a short story and not a book.
* Chapter 2, line 66, `z3998:drama` would be used for actual drama content in the book, the same way letters are semanticated with `z3998:letter` and poems with `z3998:poem`. In this case, it is only the title so it should be semanticated with `se:name.publication.play`.
* Chapter 3, line 146: *Sonata Pathétique* would be considered the full title of the composition and should be semanticated as such.
* Chapter 5, line 28: *The Ring and the Book* is a long poem like *The Odyssey* or *Paradise Lost*.
* Chapter 10, line 145: You can unsemanticate instances of incomplete *Rise of*—these aren’t complete titles and the character eventually gets it right.
* Chapter 10, lines 152 and 160: content in those blockquotes appears to be hymns.

**Comment by iesegnu** [comment]
Thanks, done!
