### ISSUE TITLE
Semanticate languages

### ISSUE THREAD

**Issue by Gragt** [iesegnu/dorothy-m-richardson_pointed-roofs#7]
* Chapter 2, lines 26–35: *zeep* is a Dutch word.
* Chapter 3, line 13: the very first mention of *Saal* should italicised to tell the reader it is a foreign word.
* Chapter 3, lines 13, 123, and 153; and Chapter 8, line 42: *raccommodage* is semanticated with emphasis but it doesn’t seem to warrant it; `<i xml:lang="fr">` should suffice.
* Chapter 3, line 39: *weiss* was corrected to *weiß*, but the character doesn’t appear to be good at speaking German. Shouldn’t her speech be left as-is to signal her lack of proficiency?
* Chapter 3, line 64: *motif* is in M-W and doesn’t need to be semanticated.
* Chapter 6, line 111: *demoiselles* and *jeunes filles* should each be wrapped in their own semanticated `<span>` because they aren’t complete clauses.
* Chapter 10, line 277: The German semantic inflection encloses *here!* which is English.

**Comment by iesegnu** [comment]
Thanks, done!
